---
version: '3.3'
services:
  post_db:
    image: mongo:${MONGODB_IMAGE_TAG}
    volumes:
      - post_db:/data_db
    networks:
      reddit:
        aliases:
          - ${DB_NETWORK_ALIAS_COMMENT}
          - ${DB_NETWORK_ALIAS_POST}
          - ${DB_NETWORK_ALIAS_EXPORTER}
    container_name: ${DB_CONTAINER_NAME}
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_TAG}
    ports:
      - ${UI_PORTS}:${UI_PORTS}/tcp
    networks:
      - reddit
    container_name: ${UI_CONTAINER_NAME}
  post:
#    build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_TAG}
    networks:
      reddit:
        aliases:
          - ${POST_NETWORK_ALIAS}
    container_name: ${POST_CONTAINER_NAME}
  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_TAG}
    networks:
      reddit:
        aliases:
          - ${COMMENT_NETWORK_ALIAS}
    container_name: ${COMMENT_CONTAINER_NAME}
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      reddit:
        aliases:
          - ${PROMETHEUS_NETWORK_ALIAS}
  node_exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      reddit:
        aliases:
          - ${NODE_EXPORTER_NETWORK_ALIAS}
  mongodb_exporter:
    image: ${USERNAME}/mongodb_exporter:latest
    command:
      - '-mongodb.uri "mongodb://${DB_NETWORK_ALIAS_EXPORTER}:27017'
    networks:
      reddit:
        aliases:
          - ${MONGO_NODE_EXPORTER_NETWORK_ALIAS}

volumes:
  post_db:
networks:
  reddit:
