---
version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data_db
    networks:
      reddit:
        aliases:
          - comment_db_host
          - post_db_host
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      reddit:
        aliases:
          - post_host
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      reddit:
        aliases:
          - comment_host
volumes:
  post_db:
networks:
  reddit:
